/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controlador.ControladorInativar;
import Relatorios.GerarRelatorios;
import Utilitarios.Mensagem;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;

/**
 *
 * @author Gabriel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    boolean btnusu;

    public static boolean Cadastro;
    public static boolean Login;
    public static boolean Item;
    public static boolean VisualizarPessoas;
    public static boolean VisualizarItem;
    public static boolean VisualizarEmprestimo;
    public static boolean Emprestimo;
    public static boolean Devolucao;

    /**
     * Creates new form TelaPrincipal
     *
     * @param aux
     * @throws java.sql.SQLException
     */
    public TelaPrincipal(boolean aux) throws SQLException {
        initComponents();

        //Pega o dia
        int ano = c.get(Calendar.YEAR);
        int mes = c.get(Calendar.MONTH) + 1;
        int dia = c.get(Calendar.DAY_OF_MONTH);
        String data_completa = dia + "/" + mes + "/" + ano;
        inativa.checar(data_completa);

        setExtendedState(MAXIMIZED_BOTH);

        jbuAdministrativo.setVisible(aux);

        //Menu//
        //Seção de Cadastros//
        JButton usu = jbUsuarios;
        JButton livros = jbLivros;
        usu.setVisible(false);
        livros.setVisible(false);
        //Seção Lançamentos//
        JButton emprestar = jbEmprestar;
        JButton devolver = jbDevolver;
        emprestar.setVisible(false);
        devolver.setVisible(false);

        //Seção administrativo//
        JButton login = jbuLogin;
        login.setVisible(false);
        //Controle de acessos//

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (Exception e) {
            Mensagem.exibirMensagem("Erro no look and feel" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmiCadastro = new javax.swing.JMenuItem();
        jmiAdm = new javax.swing.JMenuItem();
        jmiCadastroLivro = new javax.swing.JMenuItem();
        jmiAdmLivro = new javax.swing.JMenuItem();
        jmiRelatorioUsuario = new javax.swing.JMenuItem();
        jmiRelatorioItensAtrasados = new javax.swing.JMenuItem();
        jmiRelatorioItens = new javax.swing.JMenuItem();
        jmiEmprestar = new javax.swing.JMenuItem();
        jmiAdministrarEmprestimo = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jlTitleMenu = new javax.swing.JLabel();
        jbCadastro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbUsuarios = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbLivros = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jbLancamentos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbEmprestar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jbDevolver = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jbRelatorios = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jbuAdministrativo = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jbuLogin = new javax.swing.JButton();
        jdArea = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        jmiCadastro.setText("Cadastrar");
        jmiCadastro.setActionCommand("Cadastrar\nAlterar");
        jmiCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroActionPerformed(evt);
            }
        });

        jmiAdm.setText("Administrar");
        jmiAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdmActionPerformed(evt);
            }
        });

        jmiCadastroLivro.setText("Cadastrar");
        jmiCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroLivroActionPerformed(evt);
            }
        });

        jmiAdmLivro.setText("Administrar");
        jmiAdmLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdmLivroActionPerformed(evt);
            }
        });

        jmiRelatorioUsuario.setText("Usuário");
        jmiRelatorioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioUsuarioActionPerformed(evt);
            }
        });

        jmiRelatorioItensAtrasados.setText("Itens Atrasados");
        jmiRelatorioItensAtrasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioItensAtrasadosActionPerformed(evt);
            }
        });

        jmiRelatorioItens.setText("Itens");
        jmiRelatorioItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioItensActionPerformed(evt);
            }
        });

        jmiEmprestar.setText("Emprestar");
        jmiEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmprestarActionPerformed(evt);
            }
        });

        jmiAdministrarEmprestimo.setText("Administrar Empréstimo");
        jmiAdministrarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdministrarEmprestimoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setInheritsPopupMenu(true);
        jToolBar1.add(jSeparator1);

        jlTitleMenu.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jlTitleMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitleMenu.setText("BDLM");
        jlTitleMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlTitleMenu.setMaximumSize(new java.awt.Dimension(200, 40));
        jlTitleMenu.setMinimumSize(new java.awt.Dimension(200, 40));
        jlTitleMenu.setName(""); // NOI18N
        jlTitleMenu.setVerifyInputWhenFocusTarget(false);
        jToolBar1.add(jlTitleMenu);
        jlTitleMenu.getAccessibleContext().setAccessibleDescription("");

        jbCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open-folder.png"))); // NOI18N
        jbCadastro.setText("Cadastros");
        jbCadastro.setFocusable(false);
        jbCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbCadastro.setMargin(new java.awt.Insets(2, 0, 2, 14));
        jbCadastro.setMaximumSize(new java.awt.Dimension(200, 65));
        jbCadastro.setMinimumSize(new java.awt.Dimension(200, 30));
        jbCadastro.setName(""); // NOI18N
        jbCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCadastroMouseExited(evt);
            }
        });
        jbCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroActionPerformed(evt);
            }
        });
        jToolBar1.add(jbCadastro);
        jToolBar1.add(jSeparator2);

        jbUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man-user.png"))); // NOI18N
        jbUsuarios.setText("Usuários");
        jbUsuarios.setFocusable(false);
        jbUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbUsuarios.setMaximumSize(new java.awt.Dimension(200, 40));
        jbUsuarios.setMinimumSize(new java.awt.Dimension(200, 40));
        jbUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbUsuariosMouseClicked(evt);
            }
        });
        jbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(jbUsuarios);
        jToolBar1.add(jSeparator3);

        jbLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notebook.png"))); // NOI18N
        jbLivros.setText("Itens");
        jbLivros.setFocusable(false);
        jbLivros.setHideActionText(true);
        jbLivros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbLivros.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbLivros.setMaximumSize(new java.awt.Dimension(200, 40));
        jbLivros.setMinimumSize(new java.awt.Dimension(200, 40));
        jbLivros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLivrosActionPerformed(evt);
            }
        });
        jToolBar1.add(jbLivros);
        jToolBar1.add(jSeparator4);

        jbLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newspaper.png"))); // NOI18N
        jbLancamentos.setText("Lançamentos");
        jbLancamentos.setFocusable(false);
        jbLancamentos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbLancamentos.setMargin(new java.awt.Insets(2, 0, 2, 14));
        jbLancamentos.setMaximumSize(new java.awt.Dimension(200, 65));
        jbLancamentos.setMinimumSize(new java.awt.Dimension(200, 30));
        jbLancamentos.setName(""); // NOI18N
        jbLancamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbLancamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbLancamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbLancamentosMouseExited(evt);
            }
        });
        jbLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLancamentosActionPerformed(evt);
            }
        });
        jToolBar1.add(jbLancamentos);
        jToolBar1.add(jSeparator5);

        jbEmprestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notebook_2.png"))); // NOI18N
        jbEmprestar.setText("Empréstimo");
        jbEmprestar.setFocusable(false);
        jbEmprestar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbEmprestar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbEmprestar.setMaximumSize(new java.awt.Dimension(200, 40));
        jbEmprestar.setMinimumSize(new java.awt.Dimension(200, 40));
        jbEmprestar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmprestarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbEmprestar);
        jToolBar1.add(jSeparator6);

        jbDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notebook_1.png"))); // NOI18N
        jbDevolver.setText("Devolução");
        jbDevolver.setFocusable(false);
        jbDevolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbDevolver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbDevolver.setMaximumSize(new java.awt.Dimension(200, 40));
        jbDevolver.setMinimumSize(new java.awt.Dimension(200, 40));
        jbDevolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDevolverActionPerformed(evt);
            }
        });
        jToolBar1.add(jbDevolver);
        jToolBar1.add(jSeparator7);

        jbRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teste2.png"))); // NOI18N
        jbRelatorios.setText("Relatórios");
        jbRelatorios.setFocusable(false);
        jbRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbRelatorios.setMargin(new java.awt.Insets(2, 0, 2, 14));
        jbRelatorios.setMaximumSize(new java.awt.Dimension(200, 65));
        jbRelatorios.setMinimumSize(new java.awt.Dimension(200, 30));
        jbRelatorios.setName(""); // NOI18N
        jbRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRelatoriosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbRelatoriosMouseExited(evt);
            }
        });
        jbRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatoriosActionPerformed(evt);
            }
        });
        jToolBar1.add(jbRelatorios);
        jToolBar1.add(jSeparator9);

        jbuAdministrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/if_administrative-docs_59015.png"))); // NOI18N
        jbuAdministrativo.setText("ADM");
        jbuAdministrativo.setFocusable(false);
        jbuAdministrativo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbuAdministrativo.setMargin(new java.awt.Insets(2, 0, 2, 14));
        jbuAdministrativo.setMaximumSize(new java.awt.Dimension(200, 65));
        jbuAdministrativo.setMinimumSize(new java.awt.Dimension(200, 30));
        jbuAdministrativo.setName(""); // NOI18N
        jbuAdministrativo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbuAdministrativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuAdministrativoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbuAdministrativoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbuAdministrativoMouseExited(evt);
            }
        });
        jbuAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdministrativoActionPerformed(evt);
            }
        });
        jToolBar1.add(jbuAdministrativo);
        jbuAdministrativo.getAccessibleContext().setAccessibleName("Administrativo");

        jToolBar1.add(jSeparator8);

        jbuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man-user.png"))); // NOI18N
        jbuLogin.setText("Cadastrar Login");
        jbuLogin.setFocusable(false);
        jbuLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbuLogin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbuLogin.setMaximumSize(new java.awt.Dimension(200, 40));
        jbuLogin.setMinimumSize(new java.awt.Dimension(200, 40));
        jbuLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbuLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuLoginMouseClicked(evt);
            }
        });
        jbuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuLoginActionPerformed(evt);
            }
        });
        jToolBar1.add(jbuLogin);

        jdArea.setBackground(java.awt.SystemColor.control);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo_novo.png"))); // NOI18N
        jLabel1.setText("Sistema");
        jLabel1.setToolTipText("");

        jdArea.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jdAreaLayout = new org.jdesktop.layout.GroupLayout(jdArea);
        jdArea.setLayout(jdAreaLayout);
        jdAreaLayout.setHorizontalGroup(
            jdAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1181, Short.MAX_VALUE)
        );
        jdAreaLayout.setVerticalGroup(
            jdAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jdArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .add(jdArea)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastroMouseClicked

        JButton usu = jbUsuarios;
        JButton livros = jbLivros;
        if (!usu.isVisible()) {
            usu.setVisible(true);
            livros.setVisible(true);
        } else {
            usu.setVisible(false);
            livros.setVisible(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbCadastroMouseClicked

    private void jbCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastroMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_jbCadastroMouseEntered

    private void jbCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastroMouseExited

    }//GEN-LAST:event_jbCadastroMouseExited

    private void jbCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCadastroActionPerformed

    private void jbLancamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLancamentosMouseClicked
        // TODO add your handling code here:
        JButton emprestar = jbEmprestar;
        JButton devolver = jbDevolver;
        if (!emprestar.isVisible()) {
            emprestar.setVisible(true);
            devolver.setVisible(true);
        } else {
            emprestar.setVisible(false);
            devolver.setVisible(false);
        }
    }//GEN-LAST:event_jbLancamentosMouseClicked

    private void jbLancamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLancamentosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLancamentosMouseEntered

    private void jbLancamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLancamentosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLancamentosMouseExited

    private void jbLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLancamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLancamentosActionPerformed

    private void jbRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRelatoriosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRelatoriosMouseClicked

    private void jbRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRelatoriosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRelatoriosMouseEntered

    private void jbRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRelatoriosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRelatoriosMouseExited

    private void jbRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatoriosActionPerformed
        // TODO add your handling code here:
        JPopupMenu popupRelatorio = new JPopupMenu();
        popupRelatorio.add(jmiRelatorioItensAtrasados);
        popupRelatorio.add(jmiRelatorioUsuario);
        popupRelatorio.add(jmiRelatorioItens);
        popupRelatorio.show(jbRelatorios, 165, 5);
    }//GEN-LAST:event_jbRelatoriosActionPerformed

    private void jbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbUsuariosMouseClicked
        // TODO add your handling code here:

        //Menu Pop up
        JPopupMenu popup = new JPopupMenu();
        popup.add(jmiCadastro);
        popup.add(jmiAdm);
        popup.show(jbUsuarios, 165, 5);


    }//GEN-LAST:event_jbUsuariosMouseClicked

    private void jbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuariosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbUsuariosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setDefaultCloseOperation(TelaPrincipal.DO_NOTHING_ON_CLOSE);
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Deseja encerrar o sistema?", "Encerrar", JOptionPane.YES_NO_OPTION);
        if (showConfirmDialog == JOptionPane.YES_OPTION) {
            this.dispose();
        }

    }//GEN-LAST:event_formWindowClosing

    private void jbuAdministrativoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuAdministrativoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuAdministrativoMouseClicked

    private void jbuAdministrativoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuAdministrativoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuAdministrativoMouseEntered

    private void jbuAdministrativoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuAdministrativoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuAdministrativoMouseExited

    private void jbuAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdministrativoActionPerformed
        // TODO add your handling code here:
        JButton login = jbuLogin;

        if (!login.isVisible()) {
            login.setVisible(true);

        } else {
            login.setVisible(false);

        }
    }//GEN-LAST:event_jbuAdministrativoActionPerformed

    private void jbuLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuLoginMouseClicked

    private void jbuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuLoginActionPerformed
        // TODO add your handling code here:
        TelaCadastroLogin telalog = new TelaCadastroLogin();
        if (Login == false) {
            jdArea.add(telalog);
            telalog.setVisible(true);
            telalog.setposicao();

        } else {
            Mensagem.exibirMensagem("A tela de cadastro de login já está aberta");

        }
    }//GEN-LAST:event_jbuLoginActionPerformed

    private void jbLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLivrosActionPerformed

        //Menu Pop up
        JPopupMenu popup = new JPopupMenu();
        popup.add(jmiCadastroLivro);
        popup.add(jmiAdmLivro);
        popup.show(jbLivros, 165, 5);

    }//GEN-LAST:event_jbLivrosActionPerformed

    private void jmiCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroActionPerformed
        // TODO add your handling code here:
        TelaUsuario telausu = new TelaUsuario();
        if ((Cadastro) == false) {
            jdArea.add(telausu);
            telausu.setVisible(true);
            telausu.setposicao();

        } else {
            Mensagem.exibirMensagem("A tela de cadastro de usuário já está aberta");

        }
    }//GEN-LAST:event_jmiCadastroActionPerformed

    private void jmiAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdmActionPerformed
        // TODO add your handling code here:
        if (VisualizarPessoas == false) {

            TelaVisualizarPessoa telavi = null;
            try {
                telavi = new TelaVisualizarPessoa();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            jdArea.add(telavi);

            telavi.setVisible(true);
            try {
                telavi.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Mensagem.exibirMensagem("Não foi possível abrir a tela de Administração de usuários" + ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "A tela de Administração de usuário já está aberta");

        }
    }//GEN-LAST:event_jmiAdmActionPerformed

    private void jmiAdmLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdmLivroActionPerformed
        if (VisualizarItem == false) {

            TelaVisualizarItem telavi = null;
            try {
                telavi = new TelaVisualizarItem();
            } catch (SQLException ex) {
                Mensagem.exibirMensagem("Não fó possível abrir a tela de Administração de itens " + ex);
            }
            jdArea.add(telavi);
            telavi.setVisible(true);
            try {
                telavi.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Mensagem.exibirMensagem("Não foi possível abrir a tela de Administração de itens" + ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "A tela de Administração de itens já está aberta");

        }

    }//GEN-LAST:event_jmiAdmLivroActionPerformed

    private void jmiCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroLivroActionPerformed
        // TODO add your handling code here:
        if (Item == false) {
            TelaCadastroItem telaitem = new TelaCadastroItem();
            jdArea.add(telaitem);
            telaitem.setVisible(true);
            telaitem.setposicao();
        } else {
            Mensagem.exibirMensagem("A tela de cadastro de item já está aberta");
        }
    }//GEN-LAST:event_jmiCadastroLivroActionPerformed

    private void jbEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmprestarActionPerformed
        // TODO add your handling code here:
        JPopupMenu popup = new JPopupMenu();
        popup.add(jmiAdministrarEmprestimo);
        popup.add(jmiEmprestar);
        popup.show(jbEmprestar, 165, 5);
    }//GEN-LAST:event_jbEmprestarActionPerformed

    private void jbDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDevolverActionPerformed
        if (Devolucao == false) {
            TelaDevolverEmprestimo devolve = new TelaDevolverEmprestimo();
            jdArea.add(devolve);
            devolve.setposicao();
            devolve.setVisible(true);
        } else {
            Mensagem.exibirMensagem("A tela de devolução já está aberta");
        }
    }//GEN-LAST:event_jbDevolverActionPerformed

    private void jmiRelatorioItensAtrasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioItensAtrasadosActionPerformed
        gerar.GerarItens();
    }//GEN-LAST:event_jmiRelatorioItensAtrasadosActionPerformed

    private void jmiRelatorioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioUsuarioActionPerformed
        // TODO add your handling code here:
        gerar.GerarUsuarios();
    }//GEN-LAST:event_jmiRelatorioUsuarioActionPerformed

    private void jmiRelatorioItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioItensActionPerformed

        // TODO add your handling code here:
        gerar.GerarTodosItens();
    }//GEN-LAST:event_jmiRelatorioItensActionPerformed

    private void jmiEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmprestarActionPerformed
        // TODO add your handling code here:
        if (Emprestimo == false) {
            TelaEmprestimo VisualizaEmprestimo = new TelaEmprestimo();
            jdArea.add(VisualizaEmprestimo);
            VisualizaEmprestimo.setposicao();
            VisualizaEmprestimo.setVisible(true);
        } else {
            Mensagem.exibirMensagem("A tela de empréstimo já está aberta");
        }
    }//GEN-LAST:event_jmiEmprestarActionPerformed

    private void jmiAdministrarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdministrarEmprestimoActionPerformed
        // TODO add your handling code here:
        if (VisualizarEmprestimo == false) {
            TelaVisualizarEmprestimo VisualizaEmprestimo;
            try {
                VisualizaEmprestimo = new TelaVisualizarEmprestimo();
                jdArea.add(VisualizaEmprestimo);
                VisualizaEmprestimo.setposicao();
                VisualizaEmprestimo.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            Mensagem.exibirMensagem("A tela de Administração de empréstimo já está aberta");
        }
    }//GEN-LAST:event_jmiAdministrarEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TelaLogin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbCadastro;
    private javax.swing.JButton jbDevolver;
    private javax.swing.JButton jbEmprestar;
    private javax.swing.JButton jbLancamentos;
    private javax.swing.JButton jbLivros;
    private javax.swing.JButton jbRelatorios;
    private javax.swing.JButton jbUsuarios;
    private javax.swing.JButton jbuAdministrativo;
    private javax.swing.JButton jbuLogin;
    private javax.swing.JDesktopPane jdArea;
    private javax.swing.JLabel jlTitleMenu;
    private javax.swing.JMenuItem jmiAdm;
    private javax.swing.JMenuItem jmiAdmLivro;
    private javax.swing.JMenuItem jmiAdministrarEmprestimo;
    private javax.swing.JMenuItem jmiCadastro;
    private javax.swing.JMenuItem jmiCadastroLivro;
    private javax.swing.JMenuItem jmiEmprestar;
    private javax.swing.JMenuItem jmiRelatorioItens;
    private javax.swing.JMenuItem jmiRelatorioItensAtrasados;
    private javax.swing.JMenuItem jmiRelatorioUsuario;
    // End of variables declaration//GEN-END:variables
ControladorInativar inativa = new ControladorInativar();
    GerarRelatorios gerar = new GerarRelatorios();
    Calendar c = Calendar.getInstance();
}
